### ISSUE TITLE
IRC2Basic's totalSupply VarDB ?

### ISSUE THREAD

**Issue by ICONationDevTeam** [sink772/javaee-tokens#1]
https://github.com/sink772/javaee-tokens/blob/57f2b6f6e85e4d5557318a420c380e25ceb9efc1/tokens/src/main/java/com/iconloop/score/token/irc2/IRC2Basic.java#L33

Is it intended that this variable is not a VarDB ?

If the tokenSupply is modified at a later stage (from a `_mint` or `_burn` call), the SCORE state isn't updated.

Is that right ?

**Comment by sink772** [comment]
Unless the token contract is updated (via `deploy` transaction), it's not a problem to use `tokenSupply` variable as an instance field, since all the fields information would be stored in the contract state as a form of called `objectGraph`.

However if the token contract is updated, all of its static information (i.e. `objectGraph`) will be initialized.  Therefore, yes, your point is reasonable. It should have been stored using VarDB.

At the time of the IRC2 RI contract written, Java SCOREs were regarded as immutable form, so it could not be updated by default. Now we changed the policy so that Java SCOREs also can be updated without changing its address.  I will update the implementation as to use VarDB state. Thanks for your report! :+1:

**Comment by ICONationDevTeam** [comment]
Thanks for the detailed answer, I learn a lot :) 

I got a slightly related question if you have some time : 

What's the equivalent of `on_update` method in JavaSCORE ? I cannot find it in any example SCORE or documentation.

**Comment by sink772** [comment]
There is no equivalent of `on_update` in Java SCORE. The constructor will be always invoked whenever it is deployed regardless of the deployment type, either install or update.  Please note that, as I already mentioned, the static or instance variables will be initialized on deployment, and only state DB information will be preserved between the deployment.
